spring:
  datasource:
    url: jdbc:postgresql:ec9
    username: ec9
    password: QWEasd

  jpa:
    properties:
        hibernate:
          "[show_sql]": true
          "[format_sql]": true

logging:
  level:
    io:
      github:
        gotchamana: DEBUG
